definitions:
  errcode.Error:
    type: object
  model.Tag:
    properties:
      created_by:
        type: string
      created_on:
        type: integer
      id:
        type: integer
      is_del:
        type: integer
      modified_by:
        type: string
      modified_on:
        type: integer
      name:
        type: string
      state:
        type: integer
    type: object
info:
  contact: {}
  description: An expandable template API
  termsOfService: http://github.com/thisishugow
  title: Golang GIN API
  version: "1.0"
paths:
  /api/v1/tags:
    get:
      parameters:
      - description: tag_name
        in: query
        maxLength: 100
        name: name
        type: string
      - default: 1
        description: state
        enum:
        - 0
        - 1
        in: query
        name: state
        type: integer
      - description: page
        in: query
        name: page
        type: integer
      - description: page_size
        in: query
        name: page_size
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
          schema:
            $ref: '#/definitions/model.Tag'
        "400":
          description: Request Fail
          schema:
            $ref: '#/definitions/errcode.Error'
        "500":
          description: Interal Error
          schema:
            $ref: '#/definitions/errcode.Error'
      summary: Get tags
swagger: "2.0"
